### ISSUE TITLE
多言語パソコンにおいての対応

### ISSUE THREAD

**Issue by FoxInFlame** [snowsunny/narou-reader#15]
なろう朗読ということで興味を持ったため試してみたのですが、章番号以外全て飛ばして次の章を読み始めました。びっくりしたので調べてみたら、たぶん私のパソコン（もといブラウザー）の言語設定の既存値が英語なのが原因かと思われます。ブラウザコンソールで試してみても数字の発音はきれいなアメリカ英語でした。

SpeechSynthesis について少し調べたところ、言語を設定できるそうなので([`.lang`](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/lang))、なろう特化拡張機能ということもあり日本語を使用するように強制化すればどうでしょうか。

**Comment by FoxInFlame** [comment]
ついでに気づいてしまいましたが、このIssue、Roudokukaの方の問題でありこのレポではないです。すみません。

**Comment by snowsunny** [comment]
@FoxInFlame さん、返信遅くなりましたー。初めての自分以外のIssueで嬉しいです。 :relaxed: 

> このIssue、Roudokukaの方の問題でありこのレポではないです

との事ですが、こっちのリポで合ってますよー。(｀・ω・´)b
んで `lang` じゃ無くて `voice` の設定ですね。roudokukaでは既に設定出来る様にしてある感じです。
ドキュメントのリンクを貼ると↓のやつですね。
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice

んじゃなんでnovels-readerでこの設定をしていないかと言うと「まぁこの拡張機能を使う人はみんな日本語を使ってるやろ…(´ - ω - ｀)」の精神で作っていたからです… :see_no_evil: 

実は一番最初のリリース段階で「完全な外国語小説とかあったら、音声選択オプションを付けた方が良いかな？ :thinking: 」と思った事もあったのですが、結局付けなかった感じです… :innocent: 

2.0の前にやる事として、音声選択オプションの導入も検討してみますねー。
ご意見ありがとうございました。 :pray:

**Comment by FoxInFlame** [comment]
@snowsunny 

> んで `lang `じゃ無くて `voice `の設定ですね。

そうですか！音声朗読系のAPIは正直触ったことがなかったので無知ですみませんでした笑。

さすがに完全外国語小説はあまりないでしょうが、こういうリポ（レポではないですね笑）見つける人は時々ディレクトリなどの扱いがしやすいように言語環境を英語に設定してる人がいると思いますので、音声選択オプションは助けになると思います。検討してくださってありがとうございます。

一応私の方でIssueはまだ開けときますが、ご自由にどうぞ笑。

**Comment by snowsunny** [comment]
@FoxInFlame 素早い返信ありがとうございます！ :grin: :+1: 

> 無知ですみませんでした笑。

全然大丈夫でーす。無知の知を得たくらいなノリでー。 :wink: 

もしマイルストーンを設定する時はこのIssueを使わせて頂きます！ｗ d(´ - ω - ｀)b

**Comment by snowsunny** [comment]
@FoxInFlame すみません… :bowing_man: 
langオプションを試してみた所、最新のChromeでは動く様になっていました。自分が無知の知を得ました… :see_no_evil: 

以前は↓のリンク先に書いてある様に動作しなかった記憶があるのですが、ちゃんと実装されたみたいですね… :innocent: 
https://app.codegrid.net/entry/2016-web-speech-api-1#lang-

他の不具合も改めて動作確認しようってなったのでIssue作りました。(｀・ω・´)b

**Comment by snowsunny** [comment]
:memo: langオプションが使えるなら簡単に実装出来そうな気もするけど、どっちにしろ対応言語を調べる必要がありそうだからSpeechSynthesis.getVoices()しないと駄目かな？ :thinking: 
うーむ…(´ - ω - ｀)

**Comment by FoxInFlame** [comment]
> どっちにしろ対応言語を調べる必要がありそうだからSpeechSynthesis.getVoices()しなと駄目かな？

そうですね。言語選択よりはどの「人物」の音声を使うのか選択できた方がいいと思うので、オプション画面で`.getVoices()`のドロップダウンを作るのが一番だと思います。なんか空の配列等いろいろとめんどくさそうですが頑張ってください笑　(ง ^_^)ง

**Comment by snowsunny** [comment]
@FoxInFlame コメントありがとでーす。お盆休みに頑張れたら頑張ってみようと思います。 :grin:

**Comment by snowsunny** [comment]
DONEしたのでクローズー。 :+1:
